In [2]:
import numpy as np

In [3]:
x = np.array([1, 2, 3, 4, 5]) #1d array

In [4]:
y = np.array([[1,2,3,4],[5,6,7,8]])#2d array

In [5]:
zeroes = np.zeros((2,3)) #2 -rows , 3-columns
zeroes

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [7]:
a = np.arange(0,11,4)
a

array([0, 4, 8])

In [8]:
b = np.linspace(1,25,5)
b

array([ 1.,  7., 13., 19., 25.])

In [9]:
b.shape

(5,)

In [10]:
y

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [11]:
y.shape #2 rows, 4 columns

(2, 4)

In [12]:
y.size #total number of elements

8

In [13]:
y.ndim #number of dimensions


2

In [20]:
x = np.array([11,2,3,4,5])
x.ndim

1

In [21]:
x
#indexing and Slicing

array([11,  2,  3,  4,  5])

In [22]:
x[0]

np.int64(11)

In [28]:
y = np.array([[1,2,3,4],[5,6,7,8]])

In [29]:
y[1,3] #1 is index of row and 3 is index of column

np.int64(8)

In [30]:
#Slicing

In [31]:
x = np.array([1,23,4,54,5,6,7,70])

In [32]:
x[:3]

array([ 1, 23,  4])

In [33]:
y = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])

In [34]:
y

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [41]:
y[2:4,1:3]

array([[10, 11],
       [14, 15]])

In [42]:
y

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [43]:
array = np.array([1,2,3,4,5,6,7,8,9,10])

In [44]:
print(array+2)

[ 3  4  5  6  7  8  9 10 11 12]


In [45]:
print(array*2)

[ 2  4  6  8 10 12 14 16 18 20]


In [46]:
print(array/2)

[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]


In [47]:
print(array**2)

[  1   4   9  16  25  36  49  64  81 100]
