In [1]:
import numpy as np

In [2]:
array = np.array([10, 20, 0, -4, 500])

In [3]:
np.argmin(array) #it will return the index of smallest value in the array

np.int64(3)

In [4]:
np.argmax(array)

np.int64(4)

In [5]:
np.argsort(array) #it will return the index of the sorted array

array([3, 2, 0, 1, 4])

In [6]:
array1 = np.array([[1,2,3],[4,5,6]])

In [7]:
np.sum(array1)

np.int64(21)

In [8]:
np.mean(array1)

np.float64(3.5)

In [9]:
np.min(array1)

np.int64(1)

In [10]:
np.max(array1)

np.int64(6)

In [11]:
np.std(array1) #standard deviation

np.float64(1.707825127659933)

In [12]:
np.var(array1) #variance

np.float64(2.9166666666666665)

In [13]:
np.median(array1)

np.float64(3.5)

In [14]:
array1

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
np.transpose(array1)

array([[1, 4],
       [2, 5],
       [3, 6]])

NUMPY VS LIST

In [16]:
x = np.array([3,4,5,7,8,8,23,35])

In [17]:
data = [21,45,67,'hello','hey']

In [18]:
import sys
list_1 = list(range(10))

In [19]:
sys.getsizeof(list_1)

136

In [20]:
list_1

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [21]:
#getsizeof() will return the size of the object in bytes

In [22]:
arr_1=np.array(list_1)

In [23]:
sys.getsizeof(arr_1)

192

In [24]:
l = list()
sys.getsizeof(l)

56

In [25]:
x = np.array(l)
sys.getsizeof(x)

112

In [28]:
list_1 = list(range(10000000))
sys.getsizeof(list_1)

80000056

In [29]:
array_1 = np.array(list_1)
sys.getsizeof(array_1)

80000112