In [1]:
import numpy as np

In [2]:
np.random.rand(3,3) # 3x3 matrix with random numbers between 0 and 1

array([[0.41693168, 0.29119787, 0.59146599],
       [0.22366337, 0.69331356, 0.30081277],
       [0.64007842, 0.72395711, 0.79605475]])

In [28]:
#np.random.seed(5)
np.random.randint(1,10,size=(3,3))


array([[4, 7, 7],
       [1, 9, 5],
       [8, 1, 1]])

In [38]:
empty = np.empty((3,3))
empty

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [32]:
array = np.arange(12)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [34]:
array.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [40]:
arr1 = np.array([1,2])
arr2 = np.array([3,4])
arr2

array([3, 4])

In [36]:
np.concatenate((arr1,arr2))

array([1, 2, 3, 4])